DROP TABLE CHECKLISTE CASCADE CONSTRAINTS PURGE; 
DROP TABLE BEOBACHTUNG CASCADE CONSTRAINTS PURGE;
DROP TABLE BEOBACHTUNGSORT CASCADE CONSTRAINTS PURGE;
DROP TABLE Vogelart CASCADE CONSTRAINTS PURGE;
/* Benutzer darf wegen unsere Software nicht gelöscht werden
   sonst gibt es keine 
   DROP TABLE HAT_Rolle; */
/*DROP TABLE Rolle;*/
/*DROP TABLE Benutzer;*/